<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>mvw</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~T</string>
    <key>name</key>
    <string>HyperWorks-MVW</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keyword</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#disabled-statement</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keyword</key>
      <dict>
        <key>match</key>
        <string>(\*)(\w+)(\().*(\))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mvw</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.mvw</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.language.mvw</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.language.mvw</string>
          </dict>
        </dict>
      </dict>
      <key>comment</key>
      <dict>
        <key>match</key>
        <string>(\/\/.*)</string>
        <key>name</key>
        <string>comment.line.mvw</string>
      </dict>
      <key>disabled-statement</key>
      <dict>
        <key>match</key>
        <string>^\s*\w+\(.*\)</string>
        <key>name</key>
        <string>comment.line.disabled.mvw</string>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.mvw</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.mvw</string>
    <key>uuid</key>
    <string>F01F22AC-6CBB-11D9-9B10-000A95E13C99</string>
  </dict>
</plist>